- name: install git
  loop:
    - git
  package:
    name: '{{ item }}'
    state: present
  tags:
    - users

- name: create group
  with_items: '{{ users }}'
  loop_control:
    label: '{{ item.name }}'
  when: item.name in users_available and item.primary_group is undefined
  group:
    name: '{{ item.name }}'
    gid: '{{ item.uid | default(omit) }}'
    state: present
  tags:
    - users

- name: create user
  with_items: '{{ users }}'
  loop_control:
    label: '{{ item.name }}'
  when: item.name in users_available
  user:
    name: '{{ item.name }}'
    uid: '{{ item.uid | default(omit) }}'
    password: '{{ item.password | default(omit) }}'
    group: '{{ item.primary_group | default(item.name) }}'
    shell: '{{ item.shell }}'
    home: '{{ item.home | default(omit) }}'
    groups: '{{ item.groups | join(",") }}'
    generate_ssh_key: yes
    append: yes
    createhome: yes
    state: present
  tags:
    - users

- name: install homeshick
  with_items: '{{ users }}'
  loop_control:
    label: '{{ item.name }}'
  when: item.name in users_available and item.castles | length > 0
  become: yes
  become_user: '{{ item.name }}'
  git:
    repo: https://github.com/andsens/homeshick.git
    dest: '{{ item.home | default("/home/" + item.name) }}/.homesick/repos/homeshick'
  tags:
    - users

- name: clone castles
  with_subelements: ['{{ users }}', castles]
  loop_control:
    label: '{{ item.0.name }}: {{ item.1 }}'
  when: item.0.name in users_available
  become: yes
  become_user: '{{ item.0.name }}'
  git:
    repo: https://github.com/{{ item.1.name | default(item.1) }}.git
    dest: '{{ item.0.home | default("/home/" + item.0.name) }}/.homesick/repos/{{ (item.1.name | default(item.1)) | basename }}'
    force: '{{ item.1.force | default(users_castles_force) }}'
  tags:
    - users

- name: link castles
  with_subelements: ['{{ users }}', castles]
  loop_control:
    label: '{{ item.0.name }}: {{ item.1 }}'
  when: item.0.name in users_available
  become: yes
  become_user: '{{ item.0.name }}'
  command: '{{ item.0.home | default("/home/" + item.0.name) }}/.homesick/repos/homeshick/bin/homeshick -f -b -q link {{ item.1 | basename }}'
  changed_when: False
  tags:
    - users

- name: write sshkeys
  with_items: '{{ users }}'
  loop_control:
    label: '{{ item.name }}: {{ item.sshkeys.split(" ")[2] | trim }}'
  when: item.name in users_available
  authorized_key:
    user: '{{ item.name }}'
    key: '{{ item.sshkeys }}'
    exclusive: yes
    state: present
  tags:
    - users
